
export const GET_TAG_REQUEST = "GET_TAG_REQUEST";
export const GET_TAG_SUCCESS = "GET_TAG_SUCCESS";
export const GET_TAG_FAILED = "GET_TAG_FAILED";

export const TAG_CREATE_SUCCESS = "TAG_CREATE_SUCCESS"
export const TAG_CREATE_FAILED = "TAG_CREATE_FAILED"